# Generated by Django 5.1.2 on 2025-01-12 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registroconsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSUMO_ALTO', 'Consumo Alto'), ('FALLA_SENSOR', 'Falla de Sensor'), ('APAGADO_MANUAL', 'Apagado Manual')], max_length=50)),
                ('informacion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.habitacion')),
            ],
        ),
    ]
