# Generated by Django 5.1.2 on 2025-01-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='humedad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='presencia_humana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='temperatura',
            field=models.FloatField(default=0.0),
        ),
    ]
