# Generated by Django 5.1.2 on 2025-01-19 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_habitacion_humedad_habitacion_presencia_humana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.FloatField(default=0.0)),
                ('presupuesto', models.FloatField(default=0.0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='informacion',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='api.hotel'),
        ),
        migrations.DeleteModel(
            name='Piso',
        ),
    ]
