# Generated by Django 5.1.2 on 2025-01-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hotel_remove_habitacion_piso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='images',
            field=models.ImageField(default='photos/habitacion1.png', upload_to='photos/'),
        ),
    ]
