# Generated by Django 5.1.5 on 2025-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hotel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='consumo',
            field=models.FloatField(default=0.0),
        ),
    ]
