# Generated by Django 5.1.5 on 2025-01-28 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('consumo', models.FloatField(default=0.0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('images', models.ImageField(default='photos/habitacion1.png', upload_to='photos/')),
                ('presencia_humana', models.BooleanField(default=False)),
                ('temperatura', models.FloatField(default=0.0)),
                ('humedad', models.FloatField(default=0.0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AIRE', 'Aire Acondicionado'), ('VENTILADOR', 'Ventilador'), ('TELEVISOR', 'Televisor'), ('FOCO_HABITACION', 'Foco Habitación'), ('FOCO_BANO', 'Foco Baño')], max_length=50)),
                ('consumo_actual', models.FloatField(default=0.0)),
                ('apagado_remoto', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='websocket.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSUMO_ALTO', 'Consumo Alto'), ('FALLA_SENSOR', 'Falla de Sensor'), ('APAGADO_MANUAL', 'Apagado Manual')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='websocket.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.FloatField(default=0.0)),
                ('presupuesto', models.FloatField(default=0.0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='websocket.hotel'),
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='websocket.dispositivo')),
            ],
        ),
    ]
