# Generated by Django 5.1.5 on 2025-02-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='apagado_remoto',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado_remoto',
            field=models.CharField(choices=[('APAGAR', 'Apagar'), ('ENCENDER', 'Encender')], default='ENCENDER', max_length=10),
        ),
    ]
