# Generated by Django 5.1.5 on 2025-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_remove_dispositivo_apagado_remoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='consumo_desperdicio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='consumo_desperdicio_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='eficiencia_energetica',
            field=models.FloatField(default=0.0),
        ),
    ]
