# Generated by Django 5.1.5 on 2025-01-29 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_nivel_alter_habitacion_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='websocket.nivel'),
        ),
    ]
