# Generated by Django 5.1.5 on 2025-01-29 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0004_alter_habitacion_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='nivel',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='nivel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='websocket.nivel'),
        ),
    ]
