# Generated by Django 5.1.5 on 2025-01-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0005_remove_habitacion_nivel_habitacion_nivel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='nivel_id',
            new_name='nivel',
        ),
    ]
