# Generated by Django 5.1.7 on 2025-04-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0006_dispositivo_consumo_acumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='kilo_vatio_hora_costo',
            field=models.FloatField(default=1.122),
        ),
    ]
