# Generated by Django 5.1.7 on 2025-04-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0007_hotel_kilo_vatio_hora_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumo',
            name='consumo_desperdiciado',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='estado_remoto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_consumo', to='websocket.habitacion'),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='humedad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='presencia_humana',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
