# Generated by Django 5.1.7 on 2025-04-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0008_registroconsumo_consumo_desperdiciado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroconsumo',
            name='consumo_desperdiciado',
        ),
    ]
