# Generated by Django 5.1.7 on 2025-04-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0009_remove_registroconsumo_consumo_desperdiciado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroconsumo',
            name='humedad',
        ),
        migrations.RemoveField(
            model_name='registroconsumo',
            name='presencia_humana',
        ),
        migrations.RemoveField(
            model_name='registroconsumo',
            name='temperatura',
        ),
        migrations.CreateModel(
            name='RegistroPresencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presencia_humana', models.BooleanField(default=False)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_presencia', to='websocket.habitacion')),
            ],
        ),
    ]
