# Generated by Django 5.1.7 on 2025-04-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0009_remove_registroconsumo_consumo_desperdiciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(default='No hay mensaje'),
        ),
    ]
